from enum import Enum


class Currency(Enum):
    BRL = "BRL"


class MerchantStatus(Enum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"


class MerchantType(Enum):
    RESTAURANTE = "RESTAURANTE"


class MerchantCategories(Enum):
    BURGERS = "BURGERS"
    PIZZA = "PIZZA"
    FAST_FOOD = "FAST_FOOD"
    HOT_DOG = "HOT_DOG"
    JAPANESE = "JAPANESE"
    DESSERTS = "DESSERTS"
    AMERICAN = "AMERICAN"
    ICE_CREAM = "ICE_CREAM"
    BBQ = "BBQ"
    SANDWICH = "SANDWICH"
    MEXICAN = "MEXICAN"
    BRAZILIAN = "BRAZILIAN"
    PASTRY = "PASTRY"
    ARABIAN = "ARABIAN"
    COMFORT_FOOD = "COMFORT_FOOD"
    VEGETARIAN = "VEGETARIAN"
    VEGAN = "VEGAN"
    BAKERY = "BAKERY"
    HEALTHY = "HEALTHY"
    ITALIAN = "ITALIAN"
    CHINESE = "CHINESE"
    JUICE_SMOOTHIES = "JUICE_SMOOTHIES"
    SEAFOOD = "SEAFOOD"
    CAFE = "CAFE"
    SALADS = "SALADS"
    COFFEE_TEA = "COFFEE_TEA"
    PASTA = "PASTA"
    BREAKFAST_BRUNCH = "BREAKFAST_BRUNCH"
    LATIN_AMERICAN = "LATIN_AMERICAN"
    CONVENIENCE = "CONVENIENCE"
    PUB = "PUB"
    HAWAIIAN = "HAWAIIAN"
    EUROPEAN = "EUROPEAN"
    FAMILY_MEALS = "FAMILY_MEALS"
    FRENCH = "FRENCH"
    INDIAN = "INDIAN"
    PORTUGUESE = "PORTUGUESE"
    SPANISH = "SPANISH"
    GOURMET = "GOURMET"
    KIDS_FRIENDLY = "KIDS_FRIENDLY"
    SOUTH_AMERICAN = "SOUTH_AMERICAN"
    SPECIALTY_FOODS = "SPECIALTY_FOODS"
    ARGENTINIAN = "ARGENTINIAN"
    PREMIUM = "PREMIUM"
    AFFORDABLE_MEALS = "AFFORDABLE_MEALS"
